### ISSUE TITLE
Cargo plugin does not work locally

### ISSUE THREAD

**Issue by Cousjava** [Cousjava/payara-maven-test#2]
Cargo plugin looks in target/cargo/configurations/glassfish4x/domain1 to find Payara, despite being given payara.home

Occurs using both my branch and OndrejM's (#1)

Using:
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-72-generic", arch: "amd64", family: "unix"
Payara - 4.1.1.172 snapshot, recent build form master

**Comment by OndroMih** [comment]
`target/cargo/configurations/glassfish4x/domain1` is the default path to the domain if `payara.home` isn't specified. If it's specified, then an existing `domain1` in the installation should be used. I'll have to check.

More correctly:

If `payara.home` isn't specified, then Payara Server (or mabe GlassFish server, I don't know) is downloaded to the `target` directory and `domain` is created in  `target/cargo/configurations/glassfish4x/domain1`

If `payara.home` is specified and it points to a Payara Server installation, it should reuse in `${payara.home}/glassfish/domains/domain1` (or create it).

**Comment by OndroMih** [comment]
Payara server shouldn't be running when cargo plugin is used locally, because it attempts to start Payara server. If it's running, it's possible that it won't reuse the running domain and will create a new domain in `target/cargo/configurations/glassfish4x/domain1` to start a new server instance.

**Comment by OndroMih** [comment]
You're correct, also in my case the test uses ` target/cargo/configurations/glassfish4x/domain1` for the domain, even if a server isn't running and `payara.home` is set properly. I'll try to fix it.

**Comment by OndroMih** [comment]
By digging deeper, I found out that configuration `home` element needs to be specified to the domain dir path - it's used as the argument of `--domain-dir` for the `start-domain` command.

**Comment by Cousjava** [comment]
Local now works as long as Payara is not already running. If it is running then it fails with 
[WARNING] [talledLocalContainer] org.codehaus.cargo.container.ContainerException: Port number 8080 (defined with the property cargo.servlet.port) is in use. Please free it on the system or set it to a different port in the container configuration.
[ERROR] Starting container [org.codehaus.cargo.container.glassfish.GlassFish4xInstalledLocalContainer@135a8c6f] failed, now stopping container
and then is stops Payara

**Comment by OndroMih** [comment]
This is intended behavior - local attempts to start a local server before deployment and tests. This is usual with tests. 

If you start a server outside of maven, you can modify pom.xml to skip the start goal. You you want to start it from maven, specify a different admin port and domain to avoid port collision.

I though this repo is just an example to use in a blog post. I didn't design pom.xml to be flexible enough to modify the behavior only by configuration. You need to modify pom.xml if the current solution doesn't fit your setup.
